- name: Update Kotlin and Gradle
  working-directory: workspace/inkvision_build/android
  run: |
    # Force Kotlin 1.9.0 exactly (to match metadata version)
    sed -i 's/ext\.kotlin_version = .*/ext.kotlin_version = "1.9.0"/' build.gradle || true
    sed -i 's#distributionUrl=.*#distributionUrl=https://services.gradle.org/distributions/gradle-8.2-all.zip#' gradle/wrapper/gradle-wrapper.properties || true
